### ISSUE TITLE
tokenizers version

### ISSUE THREAD

**Issue by oonid** [crow-intelligence/growth-hacking-sentiment#1]
hi,
do you have any explanation about using specific "tokenizers==0.5.2"?

I got this error on Google Colab:
`ERROR: transformers 2.10.0 has requirement tokenizers==0.7.0, but you'll have tokenizers 0.5.2 which is incompatible.`

and it resolved if I changed to "tokenizers==0.7.0"

thank you.

**Comment by zolizoli** [comment]
Thank you for submitting an issue. The tokenizers version is wrong, it comes from a previous version of the project. The correct version is 0.7.0 as you wrote. We've corrected the requirements.txt. Thanks again for reporting the problem!
